<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- NETSDK1226 workaround: chybí prune-package manifest pro net10.0 u Web SDK -->
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IoT.Infrastructure\IoT.Infrastructure.csproj" />
  </ItemGroup>

</Project>
