apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: 'grafana'
    jsonData:
      database: timescaledb_iot
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: true
